# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Geo-TigerLine
version:      0.03
version_from: lib/Geo/TigerLine.pm
installdirs:  site
requires:
    base:                          0
    Carp:                          0
    Carp::Assert:                  0
    Class::Accessor:               0.15
    Class::Data::Inheritable:      0.02
    Data::Dumper:                  0
    strict:                        0
    Test::More:                    0.47
    vars:                          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
